// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5mq_sMoSo5W6tFBkYKK9BsAiNCAzhbaU',
    appId: '1:316510012357:web:fb20da680ca6ca5dffc1ac',
    messagingSenderId: '316510012357',
    projectId: 'meditriage-fee23',
    authDomain: 'meditriage-fee23.firebaseapp.com',
    storageBucket: 'meditriage-fee23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiGu5L4LosArWBzrOaJxOmsE3UpEAync',
    appId: '1:316510012357:android:dd69e23e5f99fd58ffc1ac',
    messagingSenderId: '316510012357',
    projectId: 'meditriage-fee23',
    storageBucket: 'meditriage-fee23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqpWxPj-ppI1zQUnJVPMOqKMWeKuYzU6Y',
    appId: '1:316510012357:ios:34e7f9f6ce7a7aa5ffc1ac',
    messagingSenderId: '316510012357',
    projectId: 'meditriage-fee23',
    storageBucket: 'meditriage-fee23.firebasestorage.app',
    iosBundleId: 'com.example.meditrageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqpWxPj-ppI1zQUnJVPMOqKMWeKuYzU6Y',
    appId: '1:316510012357:ios:34e7f9f6ce7a7aa5ffc1ac',
    messagingSenderId: '316510012357',
    projectId: 'meditriage-fee23',
    storageBucket: 'meditriage-fee23.firebasestorage.app',
    iosBundleId: 'com.example.meditrageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5mq_sMoSo5W6tFBkYKK9BsAiNCAzhbaU',
    appId: '1:316510012357:web:a8bcbc1664f7f5f7ffc1ac',
    messagingSenderId: '316510012357',
    projectId: 'meditriage-fee23',
    authDomain: 'meditriage-fee23.firebaseapp.com',
    storageBucket: 'meditriage-fee23.firebasestorage.app',
  );
}
